const $=s=>document.querySelector(s),idr=n=>'Rp '+Number(n||0).toLocaleString('id-ID');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const F=['id','name','cat','price','old','stok','badge','status','img','tag'];let LIST=[];
function toast(m){$('#toast').textContent=m;setTimeout(()=>$('#toast').textContent='',3000)}
async function post(body){const d=await fetch(STORE_CONFIG.apiUrl,{method:'POST',headers:{'Content-Type':'text/plain;charset=utf-8'},body:JSON.stringify({token:adminToken(),...body})}).then(r=>r.json());if(!d.ok){if(d.error==='Unauthorized')resetToken();throw Error(d.error==='Unauthorized'?'PIN salah, refresh lalu coba lagi':d.error)}return d}
async function load(){try{const q=new URLSearchParams({action:'adminProducts',token:adminToken()});const d=await fetch(STORE_CONFIG.apiUrl+'?'+q,{cache:'no-store'}).then(r=>r.json());if(!d.ok){if(d.error==='Unauthorized')resetToken();throw Error(d.error==='Unauthorized'?'PIN salah, refresh lalu coba lagi':d.error)}LIST=d.products;
$('#cats').innerHTML=[...new Set(LIST.map(p=>p.cat))].map(c=>`<option value="${esc(c)}">`).join('');
$('#rows').innerHTML=LIST.length?LIST.map(p=>`<tr class="${p.status==='NONAKTIF'?'off':''}"><td>${p.img?`<img src="${esc(p.img)}" alt="" onerror="this.remove()">`:''}</td><td><b>${esc(p.name)}</b></td><td>${esc(p.cat)}</td><td>${idr(p.price)}</td><td>${p.stok===null?'-':p.stok}</td><td>${esc(p.status||'AKTIF')}</td><td><a href="#" data-e="${esc(p.id)}">Edit</a> · <a href="#" data-d="${esc(p.id)}">Hapus</a></td></tr>`).join(''):'<tr><td colspan="7">Belum ada produk di sheet PRODUK.</td></tr>'}catch(e){toast(e.message);$('#rows').innerHTML='<tr><td colspan="7">'+esc(e.message)+'</td></tr>'}}
function fill(p){F.forEach(k=>$('#'+k).value=p?(p[k]??''):'');$('#status').value=(p&&p.status)||'AKTIF';$('#hot').checked=!!(p&&p.hot);$('#specs').value=p?(p.specs||[]).join('\n'):'';$('#ft').textContent=p?'Edit Produk':'Tambah Produk'}
$('#rows').onclick=async e=>{const a=e.target.closest('a');if(!a)return;e.preventDefault();if(a.dataset.e){fill(LIST.find(p=>p.id===a.dataset.e));scrollTo(0,0)}if(a.dataset.d&&confirm('Hapus produk ini permanen? (Gunakan status NONAKTIF jika hanya ingin menyembunyikan)')){try{await post({action:'deleteProduct',id:a.dataset.d});toast('Produk dihapus');load()}catch(x){toast(x.message)}}};
$('#reset').onclick=()=>fill(null);$('#refresh').onclick=load;
$('#f').onsubmit=async e=>{e.preventDefault();const p={};F.forEach(k=>p[k]=$('#'+k).value.trim());p.hot=$('#hot').checked;p.specs=$('#specs').value.split('\n').map(x=>x.trim()).filter(Boolean);if(!p.id)delete p.id;const b=$('#save');b.disabled=true;try{await post({action:'saveProduct',product:p});toast('Tersimpan — langsung tampil di toko');fill(null);load()}catch(x){toast(x.message)}finally{b.disabled=false}};
load();
